### PR TITLE
pyupgrade --py37-plus on maintenance branch

### PR DESCRIPTION
**Pull request by cclauss**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?

Upgrade Python syntax with https://pypi.org/project/pyupgrade

### CODE REVIEW

**Comment by cp2004** [comment]
What's changed since https://github.com/OctoPrint/OctoPrint/pull/4576#issuecomment-1184458112?

**Comment by foosel** [comment]
Looks identical to me, and as already pointed out in #4576 this is a no-go. `pyupgrade` already runs as part of pre-commit, and must NOT be run over the files targeted by this PR which is also stated in their headers.

**Comment by cclauss** [comment]
The changes to the three fragile files are compatible with both Python 2 and Python 3.

**Comment by foosel** [comment]
Can merge this, but as a heads-up, I'm in the process of switching away from Sphinx and over to MkDocs for the documentation, so all the sphinxext files are pretty much obsolete at this point and thus not something I'd personally bother with anymore as they'll go the way of the dodo soon. Want me to merge it anyhow?

**Comment by cclauss** [comment]
We can close as not really useful.

**Pull request closed without merging**
