### PR TITLE
update to knockout 3.5.1

### PR DESCRIPTION
**Pull request by j7126**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely 
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs 
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR 
    if necessary!
  * [x] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
Update knockout js to 3.5.1
This will allow the use of features introduced in the latest knockout version
Enables `createChildContextWithAs` and `foreachHidesDestroyed` knockout options to disable breaking changes introduced in knockout 3.5.1

#### How was it tested? How can it be tested by the reviewer?
This PR only effects the frontend js, it is tested by checking that no errors appear in the frontend console and that all UI features are working correctly. 

#### Any background context you want to provide?
N/A
#### What are the relevant tickets if any?
N/A
#### Screenshots (if appropriate)
N/A
#### Further notes
N/A

### CODE REVIEW

**Review by cp2004 — APPROVED** [review]

**Comment by foosel** [comment]
Thank you!

**Comment by jneilliii** [comment]
Any recommendations as to why my knockout sortable module I'm using would have been broken as a result of this upgrade? I was just doing some updates in my TPLinkSmartplug plugin which utilizes this, and I believe would also effect __several__ of my other plugins, including Tasmota. Basically it seems that the foreach loop gets broken completely and doesn't display any items in settings anymore.

module being used: https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/blob/0.9.25/octoprint_tplinksmartplug/static/js/knockout-sortable.js

binding in jinja: https://github.com/jneilliii/OctoPrint-TPLinkSmartplug/blob/8f3e9c50e25c2fca9b08c4e0f1562c9830958fb0/octoprint_tplinksmartplug/templates/tplinksmartplug_settings.jinja2#L10

**Comment by jneilliii** [comment]
never mind...found updated module that resolves the upgrade issue...now to update all my plugins....

**Comment by jneilliii** [comment]
@j7126 so I'm digging through the knockout release notes trying to figure out why my previous working bindings are now broken and noticed that in 1.5.0rc2](https://github.com/knockout/knockout/releases/tag/v3.5.0-rc2) the `createChildContextWithAs` global option was removed. So is your workaround their even necessary? 

Hopefully I'll be able to figure out why my parentContext stuff is broken, so far haven't been able to figure it out but I'm still looking. If you have any ideas for [this](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/issues/319) please let me know.

**Pull request merged**
