### PR TITLE
File/Folder renaming in OctoPrint web UI

### PR DESCRIPTION
**Pull request by sparxooo**
* [**X**] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [N/A] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [**X**] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [**X**] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [**X**] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [**X**] Your changes follow the existing coding style
  * [N/A] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [**X**] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [**X**] You have run the existing unit tests against your changes and
    nothing broke
  * [**X**] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

I've added the ability to rename files (accessed by the move dialog). You can move and rename in one operation, just move, or just rename. This code is an updated version of the previous PR (but i'm so new to git, I got lost...) so let's try again!

#### How was it tested? How can it be tested by the reviewer?

Upload some files and move them around!

I've tested as far as I can with special characters (including where OctoPrint uses a different name internally), and it seems to work (except in the case of renaming again, whereby it uses the "safe" internal name).

PyTest passes with 6 warnings (not in my touched files)

pre-commit touched some files but since passed.

#### Any background context you want to provide?

I have a Cura OctoPrint plugin which unfortunately uploads with a very generic name. I wanted to rename and move those files, and realised I couldn't.

#### What are the relevant tickets if any?

#2694

#### Screenshots (if appropriate)

OctoPrintRename

### CODE REVIEW

**Comment by fieldOfView** [comment]
> I have a Cura OctoPrint plugin which unfortunately uploads with a very generic name. 

I know this is totally off-topic, but you can change the "very generic name" in Cura by using the small pencil in the lower left of the screen. There are also two plugins that let you automatically generate the jobname from a set of parameters: Printjob Naming (by the author of the Cura OctoPrint Connection plugin - me) and Gcode Filename Format).

**Comment by sparxooo** [comment]
@fieldOfView I don't think it's off topic at all, thanks for letting me know as I didn't know that!

It's interesting how OctoPrint actually had the backend/API functionality, just that it hadn't been put into the frontend - I only noticed this on my second dig through the code (where I then removed all my added code as it was superfluous to what was already present).

This is my first ever PR to a repo so any and all comments gratefully received!

**Comment by foosel** [comment]
Sensible change, thank you for this! 👍

**Comment by sparxooo** [comment]
Hi, I've noticed I fluffed the markdown in Authors.md! It's not a breaking issue and can be fixed at some point in the future! Sorry about this :)

**Comment by foosel** [comment]
Fixed, thanks!

**Pull request merged**
