### PR TITLE
Reload logging settings when settings are viewed.

### LINKED ISSUE #3948: Logging settings don't clear when "Close" is pressed instead of "Save"
#### What were you doing?

1. Open settings dialog
2. Go to "Logging".
3. Add a few rows in the "Logging Levels" section by clicking on the blue plus sign.
4. Click "Close" and not "Save".
5. Preform an action and notice that the logging was actually not affected because I didn't hit Save (good!)
6. Re-open the settings dialog.
7. Select logging again.
8. Noticed that the logging level that I set is still listed there, even though I never saved it.

#### What did you expect to happen?

I expected the settings dialog for Logging Levels to return to the previous values.  This is what happens for other settings such as the checkboxes in the "Features" section of the settings.

#### What happened instead?

The logging levels are still there, making it look like I saved when I didn't.  (The behavior is correct in that the the setting didn't take effect and logging was unchanged!  Just the appearance is wrong.)

#### Did the same happen when running OctoPrint in safe mode?

I didn't test it but I can't imagine that it would matter.

#### Version of OctoPrint

OctoPrint 1.5.2 Python 3.7.3

#### Operating System running OctoPrint

Linux

#### Printer model & used firmware incl. version

Virtual Printer.  I don't have a printer

#### Browser and version of browser, operating system running browser

Google Chrome

#### Link to octoprint.log

During the whole testing process, no log lines were created.

#### Link to contents of terminal tab or serial.log

Nothing.  No printing was done.

#### Link to contents of Javascript console in the browser

Nothing

I have read the FAQ.

### PR DESCRIPTION
**Pull request by eyal0**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

This PR fetches the logging settings each time the setting dialog is opened.  This makes it so that if "Close" was previously used on the settings instead of "Save", the settings dialog will revert back to the unchanged settings the next time that the settings dialog is opened.

#### How was it tested? How can it be tested by the reviewer?

1. Open the Logging settings dialog.
2. Make some changes to the Log levels.
3. "Close" but don't "Save" the settings.
4. Re-open the Logging settings dialog and notice that the unsaved settings are reverted (previously they would not be).

#### What are the relevant tickets if any?

Fixes #3948

### CODE REVIEW

**Comment by jneilliii** [comment]
ooh, I wonder if this would resolve my issue using on_settings_load for transferring data to the front end as well when settings are shown. I had tried that approach and found out that it only runs that override method on OctoPrint startup it seems and I ended up switching to an API callback on the onSettingsShown in the js side of the plugin.

**Comment by eyal0** [comment]
Hold off on this merge for a second, I think there might still be small issues.

**Comment by cp2004** [comment]
Don't worry, you've got a while before any merge will happen, no earlier than working day tomorrow (CET)

**Comment by eyal0** [comment]
> Don't worry, you've got a while before any merge will happen, no earlier than working day tomorrow (CET)

It was actually a bug in maintenance #3952 which I have just filed.  Fix in #3953

**Pull request merged**
