### PR TITLE
Validate websocket JSON before sending

### LINKED ISSUE #3875: additional_state_data is broken with invalid JSON
#### What were you doing?

Trying to use the additional_state_data hook to send a dict with a value that is `float("inf")`.

1. Create a plugin in the normal way.
2. Add to the hooks: `"octoprint.printer.additional_state_data": __plugin_implementation__.additional_state_data`
3. Add this function:

```python
  def additional_state_data(self, initial, *args, **kwargs):
    return {"x": float("inf")}
```
#### What did you expect to happen?

I expected that the print time left would still be displayed on screen.

#### What happened instead?

Print time left is no longer displayed on screen.  Printer is crippled, unable to print from GUI.

#### Did the same happen when running OctoPrint in safe mode?

I didn't try this because this bug can only happen if plugins are enabled.

#### Version of OctoPrint

OctoPrint 1.5.1 Python 3.7.7

#### Operating System running OctoPrint

Linux

#### Printer model & used firmware incl. version

Virtual printer

#### Browser and version of browser, operating system running browser

Chrome

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

### PR DESCRIPTION
**Pull request by eyal0**
The default json library in python will send infinity values as `Infinity` as described [here](https://docs.python.org/3/library/json.html#json.dump).  Check that the JSON is strictly valid before sending it, otherwise throw an exception.

This fixes #3875

  * [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [ ] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

### CODE REVIEW

**Comment by eyal0** [comment]
Tested this with the same procedure as described in the PR.  The result is now warnings in the log:

```
2020-12-10 21:31:49,248 - octoprint.server.util.sockjs - WARNING - Could not send message to client 127.0.0.1: Object of type frozendict is not JSON serializable
2020-12-10 21:31:49,331 - octoprint.server.util.sockjs - WARNING - Could not send message to client 127.0.0.1: Out of range float values are not JSON compliant
2020-12-10 21:31:49,833 - octoprint.server.util.sockjs - WARNING - Could not send message to client 127.0.0.1: Out of range float values are not JSON compliant
2020-12-10 21:31:50,334 - octoprint.server.util.sockjs - WARNING - Could not send message to client 127.0.0.1: Out of range float values are not JSON compliant
```

I'm not sure why the first one is different from the rest.

**Comment by eyal0** [comment]
That first error is causing a problem.  Not sure why.  I think that it's some interaction between frozendict and regular dict.

**Comment by cp2004** [comment]
To fix the CI check errors, run `pre-commit run --hook-stage manual --all-files`

Full details about pre commit are in step 9 of the [contributing guidelines]( https://github.com/OctoPrint/OctoPrint/blob/master/CONTRIBUTING.md#pull-requests).

**Comment by foosel** [comment]
I improved on this slightly. We already do custom json encoding for the socket anyhow, I added the `allow_nan=False` there, and then went a step further and also added json validation on the data fetch from the plugins - we don't want to stop sending state updates to a connected client just because a plugin injected garbage data, so now that data will be caught right at the source and filtered out.

**Comment by eyal0** [comment]
> I improved on this slightly. We already do custom json encoding for the socket anyhow, I added the `allow_nan=False` there, and then went a step further and also added json validation on the data fetch from the plugins - we don't want to stop sending state updates to a connected client just because a plugin injected garbage data, so now that data will be caught right at the source and filtered out.

Yes, that's way better. My solution was half-broken. I'm glad this is resolved.

**Pull request merged**
