### PR TITLE
Gcode viewer hide prime

### PR DESCRIPTION
**Pull request by LazeMSS**
#### What does this PR do and why is it necessary?
Added an option for the  GCode Viewer so one can specify a string. And when provided the GCode Viewer will search for this string, and if found, skip all gcode up until this string. This can be used to skip prime nozzle gcode in the preview

#### How was it tested? How can it be tested by the reviewer?
On my own instance :)

Notice that the way the gcode is "sliced/cut" has been tried with many different ways for speed and mem consumption.
https://jsben.ch/9cwLJ - indexOf seems to be fastest on all browsers tested - firefox has includes 3% faster but then again chrome is the most used browser and is much faster using indexOf

The way the gcode "cut" is implemented is to find a line starting with the entered string and cut everything before that point and comment anything remaining out of that line. So if one is search for "; layer 1" it wil search for "\n; layer 1" - and if found in a string like this: "Blah\nBlah2\nBlah3\n; layer 1 Blah4 Blah\nBlah5\nBlah6" then the string sent to the viewer will be: "; Blah4 Blah\nBlah5\nBlah6". 

Converting the gcode into single lines and parsing line by line - this would cause slowness and memory consumption beyond what I prefer. 

The current solution is a compromise between something "easy" for the enduser and also fast and memory efficient.

### CODE REVIEW

**Comment by shadycuz** [comment]
@LazeMSS  Could you provide a screenshot of the before and after gcode viewer in the PR description?

Would this functionality have also been doable as a plugin?

**Comment by LazeMSS** [comment]
@shadycuz  yes it was original thought as a plugin but it seemed more nice to include it in the main.

Disabled
image

Enabled:
image

**Comment by shadycuz** [comment]
ahh, so it brings the actual object into the center of the screen which gives a nicer field of view. Noice feature!

**Comment by LazeMSS** [comment]
@shadycuz  yes I don't personally need to see the prime line in my gcode - that is not that important :)

**Pull request merged**
