### PR TITLE
Fix two comma splices

### PR DESCRIPTION
**Pull request by endrift**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?

Fix two comma splices, which are minor grammatical errors. This is an extremely minor, nitpicky PR, but it is a fix nonetheless.

#### How was it tested? How can it be tested by the reviewer?

It wasn't tested (sorry), but it just changes strings. I'm unsure it affects localization, but I don't think these strings are localized as-is. If anything tests on these exact strings I can modify the tests, but I didn't find anything when I looked.

#### Any background context you want to provide?

https://www.merriam-webster.com/grammar/maybe-you-like-comma-splices-maybe-you-dont

These could also plausibly be fixed by replacing the comma with a semi-colon instead of adding a conjunction.

#### What are the relevant tickets if any?

None

#### Screenshots (if appropriate)

N/A

#### Further notes

This is such a minor PR that I don't consider this a "proper" contribution and don't mind it being uncredited. I just figured it would be better to fix it myself than to ask someone to fix it for me.

### CODE REVIEW

**Review by cp2004 — APPROVED** [review]
I'm happy with this, it does read better

**Comment by endrift** [comment]
Oh no you replied with another comma splice :scream: 

oh wait it doesn't matter when it's just a comment

**Comment by cp2004** [comment]
It's ok, it's just a comment

...

**Comment by foosel** [comment]
Thank you, it's been merged. (SCNR)

Will be released with 1.11.0.

**Pull request merged**
