### PR TITLE
improvement/issue3868

### LINKED ISSUE #3868: [Request] Remember (and restore) last opened folder in Files list
Currently, the "Files" list is reset (at the root of files) each time octoprint is loaded.
I'd like it to be restored on the last opened folder.

### PR DESCRIPTION
**Pull request by thelastWallE**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
fixes #3868 Saves the curent Path to the localStorage and loads it again after a reload of OctoPrint

#### How was it tested? How can it be tested by the reviewer?
local windows machine with vsc "Run and Debug"
 
#### What are the relevant tickets if any?
Issue #3868

#### Further notes
The listStyle setting can also be refactored into this new optionsLocalStorageKey, so that it is all in one place.

### CODE REVIEW

**Comment by foosel** [comment]
Hmmm... I'm now wondering if this change in behaviour should be controllable by a setting tbh. Something under Features maybe like "remember selected folder" or something?

**Comment by thelastWallE** [comment]
"Remember selected folder in file list" ?

**Comment by foosel** [comment]
Yep!

**Comment by thelastWallE** [comment]
needs testing

**Comment by thelastWallE** [comment]
- [ ] adding feature finished
- [ ] testing
- [ ] finished

**Comment by thelastWallE** [comment]
- [x] tested with vscode and python 3.9.2

**Review by foosel — APPROVED** [review]

**Pull request merged**
