### PR TITLE
Webrtc: fix RTCSessionDescription

### PR DESCRIPTION
**Pull request by havalli**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?
Fixed the connection to the webrtc server. 

#### How was it tested? How can it be tested by the reviewer?
Tested with a [mediamtx](https://github.com/bluenviron/mediamtx) Webrtc server
Webcam url: "webrtcs://webrtc-server-host/cam/whep"

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by cp2004** [comment]
The (incomplete) WebRTC implementation in OctoPrint is only compatible with the aiortc server it was developed for (by another contributor). This change will probably break that and any similar servers that communicate the same way.

Because there is no standard to the WebRTC offer communication, these should use a Webcam Plugin introduced in 1.9.0, which allows you to customise the connection to whichever server you are using. I've written one for camera-streamer.

**Comment by havalli** [comment]
There is a standard for the WebRTC offer information. [Whep](https://www.ietf.org/id/draft-murillo-whep-02.html). Yes, it is still a draft. But it fits this scenario exactly. (Just consuming a video stream)
My changes follow this standard. Wouldn't it make sense to put the existing logic in an "aiortc" webcam plugin and implement the Whep standard in the Classic Webcam?

**Comment by foosel** [comment]
Are these changes all that is needed to make it Whep compliant? If so I would suggest to add a config option to the plugin, something like `negotiate_flavor`, and depending on whether this is set to `aiortc` or `whep` do one or the other thing.

**Comment by havalli** [comment]
In my setup, it works. I think it's more of a starting point. Whep is also still a draft. I like the configuration option, but my Python skills are very bad. Maybe someone else can implement it.

**Comment by foosel** [comment]
Converting this to draft for now, as we cannot merge it as is. Requires a `negotiate_flavor` configuration option from the current point of view, in order to not break compatibility with existing aiortc based setups.

**Comment by foosel** [comment]
FWIW, latest document on WHEP seems now to be here: https://datatracker.ietf.org/doc/draft-ietf-wish-whep/, the prior link gives a 404.

Still a draft though, currently expiring in a month.

And given how long that's now been in draft-only state, I'd rather not do anything here (trying to hit a potentially moving target) and rather wait until it turns from draft to an RFC and thus something more stable. Thus, I'm closing this.

**Pull request closed without merging**
