### PR TITLE
Changes the default sorting of the "Install new Plugins..." modal

### PR DESCRIPTION
**Pull request by martellaj**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
This PR changes the default sorting of the "Install new Plugins..." modal to "popular" instead of name. As a new OctoPi user, I was very interested in checking out available plugins to extend the functionality of the service. When I clicked "Get More...", I was surprised to see it simply sorted by name.

Sorting by name doesn't tell me much. I don't know how popular (i.e. how useful other users find each plugin) plugins are, if plugins are trustworthy or well-tested (maybe they have few users), and sorting this way also promotes very specific naming choices... (i.e. the first app listed doesn't even list its actual name as it's title, but chose an "A" word instead).

#### How was it tested? How can it be tested by the reviewer?
Admittedly, I didn't build the source code. I just looked at the JS file, determined which "sort" values there are and chose the corresponding one.

#### Any background context you want to provide?
Context provided in the first question. 👍

#### What are the relevant tickets if any?
None that I could find.

#### Screenshots (if appropriate)
No UI change (just a different default setting).

#### Further notes
None.

### CODE REVIEW

**Comment by kantlivelong** [comment]
Just my 2c. I think this PR would have a lot more value if it was implemented as a sort option instead of just replacing the hardcoded value. As the PR stands I can see other users asking for sort by name to be preferred.

**Comment by martellaj** [comment]
It's already a sort option - and I believe your sort option is sticky once you change it.

The point of the PR is to change the default to avoid the "phone book" problem of people just choosing A-names for plugins so they rise to the top. 👍

**Comment by jneilliii** [comment]
@martellaj is correct. This sort option is the equivalent of what's listed as `sort by active instance count` in the sort options of Get More.

**Comment by kantlivelong** [comment]
Doh! I must be in the dark ages thinking it wasn't an option. 🥇 

There goes my pennies...

**Comment by kantlivelong** [comment]
In that case yeah makes sense. Should help reduce "top plugins" questions as well.

**Comment by foosel** [comment]
Yep, agreed, makes sense indeed!

**Review by foosel — APPROVED** [review]

**Pull request merged**
