### PR TITLE
Import ABC from collections.abc for Python 3.10 compatibility.

### PR DESCRIPTION
**Pull request by tirkarthi**
* [ ] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [ ] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

Importing ABC directly from collections has been deprecated and removed in Python 3.10 . This PR updates the relevant places

#### What are the relevant tickets if any?

Similar to #3735

### CODE REVIEW

**Comment by cp2004** [comment]
Would it be possible for these to be behind error handled blocks and against the maintenance branch, so it can go out before the 2.0.0 release dropping Python 2? That would be the ideal here, using some error handling to make it work on Python 2.7 as well.

Also, as a side note - these were *finally* removed in Py 3.10? It's been warning about it being removed for Py3.8, then 3.9, then 3.10....

**Comment by cp2004** [comment]
I tried to give this a test, while it *probably works* on Python 3.10 there's a slightly larger issue with frozendict:
```python
Traceback (most recent call last):
  File "C:\Users\charl.TERRANCE\Development\venv310\Scripts\octoprint-script.py", line 33, in <module>
    sys.exit(load_entry_point('OctoPrint', 'console_scripts', 'octoprint')())
  File "c:\users\charl.terrance\development\octoprint core\octoprint\src\octoprint\__init__.py", line 913, in main
    from octoprint.cli import octo
  File "c:\users\charl.terrance\development\octoprint core\octoprint\src\octoprint\cli\__init__.py", line 282, in <module>
    from .dev import dev_commands  # noqa: E402
  File "c:\users\charl.terrance\development\octoprint core\octoprint\src\octoprint\cli\dev.py", line 259, in <module>
    def dev():
  File "c:\users\charl.terrance\development\venv310\lib\site-packages\click\core.py", line 1377, in decorator
    cmd = group(*args, **kwargs)(f)
  File "c:\users\charl.terrance\development\venv310\lib\site-packages\click\decorators.py", line 130, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "c:\users\charl.terrance\development\venv310\lib\site-packages\click\decorators.py", line 98, in _make_command
    return cls(
  File "c:\users\charl.terrance\development\octoprint core\octoprint\src\octoprint\cli\dev.py", line 26, in __init__
    from octoprint.util.commandline import CommandlineCaller
  File "c:\users\charl.terrance\development\octoprint core\octoprint\src\octoprint\util\__init__.py", line 27, in <module>
    import frozendict
  File "c:\users\charl.terrance\development\venv310\lib\site-packages\frozendict\__init__.py", line 16, in <module>
    class frozendict(collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```
It does not appear to be maintained any longer, though there are alternatives around and people trying to claim the frozen dict project to bring it up to speed.

**Comment by tirkarthi** [comment]
Thanks added try/except and rebased. This was delayed couple of times and removed in https://github.com/python/cpython/pull/23754 for Python 3.10

**Comment by cp2004** [comment]
That looks good to me - obviously the problem of frozendict dependency will have to be solved as well (and maybe something else) but this is at least part of it. 3.10 is still in alpha, so we have 6 months or so to come up with a solution 🙂.

I did poke about and saw there was a request for the frozendict package to be adopted on PyPi that was approved, the original maintainer is OK for it to be transferred. So once they get through the backlog it may be simple enough to upgrade - though my bets are it won't support Python 2. Maybe by then we will be closer to a working 2.0 release 😉

**Comment by foosel** [comment]
Took the liberty to squash and change base to `maintenance` (since `devel` is Py3 only the Py2 fallback otherwise wouldn't really make sense either).

**Pull request merged**
