### PR TITLE
Add a few unit tests for `helpers.js`

### PR DESCRIPTION
**Pull request by richardsondev**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
Adds more unit tests for methods contained within the `helpers.js` file.

#### How was it tested? How can it be tested by the reviewer?
Validated the existing tests here are passing and that the new tests pass. This is done by opening `test-helpers.html` in a browser and verifying no errors appear.

#### Any background context you want to provide?
Since the want for more unit tests was mentioned on OctoPrint On Air, I'm adding more tests where possible. I'll be adding more in the future too.

#### What are the relevant tickets if any?
N/A

#### Screenshots (if appropriate)
N/A

#### Further notes
Added the new function `fetchWindowLocation()` to enable unit testing of methods that call `window.location`.

### CODE REVIEW

**Comment by foosel** [comment]
Hi @richardsondev, wow, thank you for this!

Can you please explain how to RUN these tests from the command line, or - better yet - add executing them to the CI workflow in `.github/workflows/build.yml` as well? :)

**Comment by cp2004** [comment]
I'm not sure if they can be. The way OctoPrint's front end tests have been setup in OctoPrint is by opening the `test-helpers.html` file in the browser.

They don't seem to have got much attention since they were first added in 2015 (apart from this PR and the other one #4490) - if more JS tests (which seems sensible to me) then maybe looking into a different way of running unit tests would be better.

The way I can imagine it being run is through node, which wouldn't be an equivalent environment to the browser so not necessarily representative tests - something to consider.

**Comment by richardsondev** [comment]
I think I was able to find a solution in PR #4534 by using [`node-qunit-puppeteer`](https://github.com/ameshkov/node-qunit-puppeteer)

Behind the scenes a headless Chromium instance is used to run the tests.  Luckily, the workflow image (`ubuntu-latest`) already includes Chromium installed: https://github.com/actions/virtual-environments/blob/ubuntu20/20220515.1/images/linux/Ubuntu2004-Readme.md

Open to all suggestions here - including suggestions for a different framework for these tests 👍

**Comment by foosel** [comment]
I feel very stupid right now because I completely forgot about my experiments with frontend tests and somehow also misread this PR regarding this 😅 Apologies 🙇‍♀️

The solution with qunit puppeteer sounds great, thank you very much for that research!

**Pull request merged**
