### PR TITLE
Adding A Remote Access OctoPrint Setup Wizard Page

### PR DESCRIPTION
**Pull request by QuinnDamerell**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?

Gina and I were discussing offline back in December that it would be nice to add a setup page for remote access, mostly to make it clear to users that doing things such as port forwarding aren't secure at all. Having a page about remote access also helps OctoPrint stay competitive with the new "all in one" solutions, where the 3D printer comes with control software, a cloud service, and an app that's all wrapped up into a closed ecosystem. 

This page informs the user that they should never port forward, links to the remote access plugins category so the user can see all of the plugins, and suggests the top 2 plugins as possible options.

Gina and I were originally talking about allowing this page do to a plugin install directly from the wizard, so then, after one more quick wizard page, the remote access was totally set up. But due to the difficulty of invoking the plugin install from the wizard, this is just the first step of getting something in place.

#### How was it tested? How can it be tested by the reviewer?

I tested this using a local raspberry pi that I flashed to the latest version of OctoPrint, applied the changes to, and then walked through the setup. I tried to test all of the scenarios, such as a fresh install, a user who already had an OctoPrint setup, and such.

#### Any background context you want to provide?

See above :)

#### What are the relevant tickets if any?

None

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by jneilliii** [comment]
I feel like only supplying Obico and OctoEverywhere links in the wizard is a little short sighted. There's also SImplyPrint, ngrok, AstroPrint, etc.

https://plugins.octoprint.org/topics/remote_access/

**Comment by QuinnDamerell** [comment]
@jneilliii I was actually just thinking about that; I will add more of them.

**Comment by foosel** [comment]
Might make sense to fetch the category from plugins.octoprint.org. Though, right now there is no export. That can be easily changed though, and we even could add some avatar like icons... Then just fetch client side, and randomise to not come off as biased. Or sort by popularity.

**Comment by QuinnDamerell** [comment]
Yeah, I think pulling them eventually would be nice, so they don't have to be updated. But the icon issue is a problem as you said. 

For now I was going to add the top 5, and then add another button at the bottom of the UI that links to the remote access page. I already had that link at the top, but it's kind of small.

**Comment by QuinnDamerell** [comment]
@jneilliii @foosel I updated the UI with the top 5 and the show-all button. In the future, an icon field can be added to the plugin repo, and then as you suggest, it could try to query from the plugin repo. The other issue that would need to be handled would be if there's no internet connection, which renders this kind of useless anyways, but the UI might look strange if it doesn't load anything.

**Comment by QuinnDamerell** [comment]
Some of the automation failed, but it doesn't look related. Does anyone know if the breaks might be related, or is that test some what flakey?

**Comment by cp2004** [comment]
In general I'm against this idea, perhaps that viewpoint can be changed with some convincing. I don't like the idea of OctoPrint advertising 3rd party services that exist for users to pay them a subscription fee so prominently in the UI, and I don't like the biased nature of the approach here.

This PR in it's first form felt _very_ biased towards OctoEverywhere to me, especially since it included that service plus just one other, and given who has submitted it that way. We have no way of measuring the increase in revenue that submitting this PR would have given your service, potentially at the expense of other cloud services, when a level playing field would be better. 5 plugins to fill in the space is still very limited to those plugins that you've chosen that exist at this moment in time, in a specific order. If someone comes along with a new cloud service tomorrow, at what point should they be added to this list, and does that mean one of the others gets taken off? Why don't all of the entries get a logo to go along with their advert space? And who has come up with the tagline advertising the plugins? In my opinion the authors of the plugins should get to set that. We will almost certainly end up with PRs wanting to adjust their adverts.

Way back I remember [reading your comment](https://github.com/OctoPrint/octoprint.org/pull/14#issuecomment-829601617) about the link in the 'Safe remote access' blog post about the noticeable volume of traffic that link was driving to the service and how much changing the order there impacted it. I think we need to be quite careful about what these spaces are used for.

I don't think it should be hardcoded into the templates, I would probably only support this idea if _at a minimum_ it was a list that could be fetched from the plugin repository by OctoPrint, so that it could change in the future. We've had 9 months since the last OctoPrint release that would be allowed to change something like this, so we are likely to end up with grumpy cloud service maintainers if for example their logo or brand name or tagline changed to something different but they couldn't change their most prominent first advert (imo) to OctoPrint users, or as I mentioned above a new cloud service comes along. I agree with Gina that the order should be randomised as well at a minimum. The Raspberry Pi Imager for example randomises the list of 3rd party images there to avoid bias towards particular projects.

**Comment by QuinnDamerell** [comment]
@cp2004 that's totally fair, and I understand where you're coming from on all of your points. Let me try to add a little context.

First, about the tagline text, icons, and content. I agree with you; I tried my best to develop text that I thought represented teach service and promoted its strong points, but I'm sure each developer would do better. For the icons, I also tried my hardest to make the best representation of the icon of the service as good as possible, but it took me a long time to even get the two in.  It took me a long time to find a suitable icon to make round and then get it all looking clean. When I went to add the others, I realized 1) I didn't have the time to get the icon for the other two services and 2) the plugin doesn't really have an icon. So I decided to leave them with no icons. My thought was that each service could circle back and update its icon/tagline as they wished if they desired to do so. I fully support some kind of "pull it from the service" approach, but I don't have enough time to add all of that logic, and I think it would require more changes to the plugin system to add some needed information. 

I also wanted to add some context that I didn't include from Gina's and my original conversation about something like this. This all came about because I was looking at the landscape of 3D printing and noticed the trend of basic 3D printers getting smarter and smarter, and the companies who make them staring to build closed garden all-in-one software control systems. The biggest example of this would be the x1 carbon, which is a great printer and great software system, but there's no choice for the user. You get the printer, connect it to Wifi, set up their app, and that's what it is.

So I was trying to think of ways that OctoPrint could stay competitive with systems like the X1 Carbon, Prusa Connect, etc. My goal with OctoEverywhere has always been (and still is) to empower the worldwide maker community. I try to keep OctoEverywhere "as free as possible", so it's accessible to all. As of now, I can offer unlimited remote access to the entire web portal, 20 seconds of full webcam streaming, medium-size file transfers, and even unlimited AI failure detection, all 100% for free. The bar I try to hold the service to is "you should be able to do everything you need to do without paying anything." I'm happy with where all of the limits currently are; the only one I wish I could make higher is the file size limit. As the support from the community ebbs and flows, I try to adjust the limits to increase them. Overall, things are still trending up, and more users = more scale, more scale = lower operational costs per user, and lower operations costs per user = high free account limits.

Anyways, I might have rose-colored glasses on since I'm not really considering my revenue, user base, or whatnot. What I originally proposed to Gina would be something very extreme, where OctoEverywhere could be something like the built-in, free, and secure remote access solution for OctoPrint. Again I didn't want to do that for any business reason of my own, but the goal would be to give all of the users of OctoPrint free and secure remote access to make their printing better. To me, I think the remote access is a game changer in how powerful OctoPrint is, and I thought of it as my service was doing this great thing for the maker community, with no strings attached, just "as free as possible" could access to OctoPrint.

So, in the end, the main goal I was trying to set out to accomplish was to provide the OctoPrint community with 1) secure and easy-to-set-up remote access and 2) a service that gives them full access to the OctoPrint portal since that's what a user who installed OctoPrint would expect to see. How we got to this point is the windy store I told above, hahaha. I still think for the betterment of the OctoPrint community, having some information in the UI about remote systems would be beneficial. But I also totally agree that the setup of the information could be much more complex. To me, this was just the first step of getting something in place. 

I would love to hear what you're thoughts are Charlie!

**Comment by cp2004** [comment]
> I fully support some kind of "pull it from the service" approach, but I don't have enough time to add all of that logic, and I think it would require more changes to the plugin system to add some needed information.

I would rather do things correctly the first time, and implement it as well as possible than to make a quick effort at it now to get a foot in the door, only for it to be ripped out and changed at a later date. 1.9.0 is done & the release notes are written so it's not making it in there, so there is plenty of time for it to be done properly - while I can hope the wait for the next OctoPrint release is not 9 months, it will certainly be a few months minimum.

> I try to keep OctoEverywhere "as free as possible", so it's accessible to all.

I do appreciate that *you* may be trying to make your service as free as possible, but unfortunately there is nothing to say that the other cloud services you chose to feature follow that viewpoint, or that someone else doesn't launch a new cloud service next week where they intend to make their money from OctoPrint users. I still think that we need to be very careful about what & how adverts (if any) get put in the UI.

**Comment by QuinnDamerell** [comment]
@cp2004 yeah, I get all of that. 

I had a thought. I know I don't have time to figure out how to update the plugin repo, make a queryable API, add the logic in the panel, handle no connection, etc. I know everyone else is really busy here as well, so I doubt anyone is super hungry to pick that up. 

But, I think the added remote access page would really be beneficial to users, for the reasons I put above. So how about we update the UI I have to not any of the plugins directly listed on it, but instead just have a link to the plugin repo's existing remote access section. I think that would mitigate your concerns until the time is found to add the rest of the stuff and possibly surface the plugins directly in the UI. 

What do you think?

**Comment by jneilliii** [comment]
That seems like a good compromise to me.

**Comment by QuinnDamerell** [comment]
@jneilliii @foosel @cp2004 I updated the PR to be as we discussed above; here's an image of it now:

image

Let me know what you think!

**Comment by QuinnDamerell** [comment]
@fieldOfView, good catch, thanks!

**Comment by QuinnDamerell** [comment]
I tired to rebase the maintenance branch to fix the test issues possibly. If not, I will keep looking into them.

**Comment by foosel** [comment]
Finally got a chance to look at this! 🥳

Given that we now have it pretty static after the above discussions (no `seen` needed anymore, not even a view model frankly), how about adjusting the "Finish" page in the wizard to make things more clear & more visible *there* instead of having this as its own step: 

image

It's been mentioned in there before, but it was less in your face, maybe these changes already achieve better visibility of the fact that no, port forwards are NOT recommended. The added icons are supposed to help see that these are TWO items to read.

We *could* also add checkboxes to both items that need to be checked off to finish the wizard ("I've read and understood this"), but that might be pushing it too far?

Thoughts?

**Comment by QuinnDamerell** [comment]
Yeah, the checkbox would be a good idea since it's safety-related. I suggest adding a check box under each item to enforce reading both.

My only fear with this UI is that since the "Hey there are remote plugins!" text is buried into the main text block, it might be ignored. It also doesn't look like a link, so users might not think to click it. 

Expanding on the ideas a little more, plugins are a really important part of OctoPrint and make it super powerful.  Right now, if a user just installs OctoPrint with no other knowledge, they have to discover plugin support and what's available by going all the way down: Settings -> Plugin Manager -> "Get More". 

I would think exposing users to the idea of plugins and what they can do might be a nice addition to the OctoPrint intro. I'm not exactly sure how or what, but it would be cool to be like... "Power up and customize your OctoPrint with plugins! Plugins can add advance functionally, customizability, remote access, notifications, and more!" And then have something that either links the user to the "Get Plugins" pop-up directly, or something that tells them where to look in the Settings UI.

That's just my thoughts, what do you all think?

**Comment by foosel** [comment]
Also I just realized that I've been happily hijacking the discussion in a PR (for some reason I thought I was looking at an issue 🙈), so I have pushed my changes to a branch and opened a PR for that here: #4833. Best further discuss the current direction there.

And @QuinnDamerell - I hope you won't take it personally that in the end we might go with mine rather than yours. I really appreciate you brought this up, and all the thought and work you put in there. I'm just trying my best to find a balance between various requirements and wishes - as always 😅

**Comment by QuinnDamerell** [comment]
No problem at all! I totally understand and I think your solution here is great.

What you said about a quick “first-time guide” would be amazing, I personally know a number of people who never realized the power of plug-ins in OctoPrint, because they didn’t know they existed! But it does sound like a chunk of work, so it would be better off in a new discussion. 

Thanks!

**Pull request closed without merging**
