### PR TITLE
Add terminal filter for busy protocol

### PR DESCRIPTION
**Pull request by Sophist-UK**
* [X] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [X] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [X] Your PR targets OctoPrint's devel branch if it's a completely 
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs 
    against master or anything else please)
  * [X] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [X] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR 
    if necessary!
  * [X] Your changes follow the existing coding style
  * [X] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [X] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
This PR adds an additional matching string to the Suppress Wait Response terminal message filter to filter out messages of the form: "Recv:echo: processing".

#### How was it tested? How can it be tested by the reviewer?
This was tested on my 3D printer. To test it you simply need to create a move which takes a long time - say a move from one extreme to the other on the z-axis. Test this both without the filter and using the existing filter and you should see several "Recv:echo: processing" messages appear in the terminal window. Change the filter regex, reload the OctoPrint browser window, and retry and these messages should be filtered.

#### Any background context you want to provide?
No

#### What are the relevant tickets if any?
N/a

### CODE REVIEW

**Comment by jneilliii** [comment]
Screenshot_20200913-100222_Chrome

Why not just add this to your terminal filters, that's what they are there for...?

**Comment by Sophist-UK** [comment]
@jneilliii I have - the purpose of this PR is to make the fix available to everyone else.

**Comment by foosel** [comment]
I'm happy to merge this, however it needs to be a separate entry than "wait" responses (those are NOT the same!) and it should capture all busy responses, not just the processing ones IMHO.

**Comment by Sophist-UK** [comment]
@foosel 

1. What is the difference from a user perspective, rather than a technical perspective, between a wait response and a busy response? If there is no difference, then shouldn't there be a single filter for them both?

2. What other busy responses are there? Can you point me to a list?

**Comment by cp2004** [comment]
Wait means the buffer is full, busy means that there is a long command eg. Homing, or probing, heating, etc.

You could just filter based on `busy` and ignore the processing bit?

**Comment by foosel** [comment]
> Wait means the buffer is full

Wrong, but an easy mistake to make :)

`wait` means: Hi, I no longer have any planned moves in my buffer, if you are currently printing something is wrong and you might want to send more data, thanks.

`busy` means: Hi, I'm currently busy AF, please don't send any more commands until I tell you it's `ok` to do so, thanks.

So completely the opposite situation. Lumping them together is just wrong, especially since you should usually never see one (`wait`) while printing unless you have some severe data corruption going on.

I'd suggest to add "Suppress busy responses" with pattern `Recv:\s*echo:\s*busy:`

**Comment by Sophist-UK** [comment]
Ok. I can see that these are different enough to warrant a separate filter - I will make this change.

(Ideally we might want to apply the wait filter only when OctoPrint believes that the printer is idle - but that sort of logic is outside the scope of this PR.)

**Comment by foosel** [comment]
None of these filters will ever be enabled unless the user explicitly enabled them (and frankly, if I wasn't sure it would make a lot of people very angry I'd get rid of this whole filtering since it makes a lot of stuff way more complicated than it needs to be and has masked up firmware issues in the past when all users shared was a terminal screenshot) and the filtering will stay strictly frontend side, so I'd rather not start to build in code that tries to intelligently toggle them in this or another PR ;)

**Comment by Sophist-UK** [comment]
Exactly - automatic toggling is way too complicated.

**Comment by Sophist-UK** [comment]
Hopefully the regex will pick up `Recv:echo: busy now` but not `Recv:echo: unbusy` or `Recv:echo: busyest`.

I have tested this in my live OctoPrint but not run unit tests (which don't exist for wait or busy filters) or compiled OP to test it in a new install,

**Comment by Sophist-UK** [comment]
On reflection perhaps I should have used `\w`.

**Comment by foosel** [comment]
Just use `Recv: (echo:\s*)?busy:` (making the `echo:` optional contrary to my initial proposal up there, and making the whitespace after `Recv:` static as that gets injected by OctoPrint anyhow).

There's no reason for checking for prefixes other than `echo:\s*`, see the [reprap wiki](https://reprap.org/wiki/G-code#Replies_from_the_RepRap_machine_to_the_host_computer) (that's the closest that we have to a standard) and it would be wrong to filter anything that doesn't match (for that users can add their own filters if they want, we only want to support the actual busy protocol here, nothing more, nothing less). This `echo:` thing there isn't actually even supposed to be there, but most firmware still have it in (without whitespace mind you) and thus OctoPrint supports it too. 

It also suffices to match only parts of the string - we don't do a full match here but only "is this pattern in this line".

Your regex would currently match `echo: here's some additional text and maybe a busy: processing` but not `busy: processing`, and that's incorrect.

image

image

As a reference, this is the busy protocol implementation in OctoPrint: https://github.com/OctoPrint/OctoPrint/blob/bdb68ae28b98beac18ba9544da553ae325a0f1db/src/octoprint/util/comm.py#L1728-L1752

**Comment by Sophist-UK** [comment]
Hmm - according to the reprap wiki:
> Examples: busy: processing, busy: paused for user

[Marlin v2](https://github.com/MarlinFirmware/Marlin/blob/9913333c33d234264a9072630e8b5ffbf07bad7e/Marlin/src/core/language.h#L135) defines the following strings: 
```
"busy: processing"
"busy: paused for user"
"busy: paused for input"
```
It seems to me that a paused string is of more interest to users than processing, so IMO we should revert back to filtering only `busy: processing`.

If there is agreement on this, I will make this further change and we should be good to go.

**Comment by Sophist-UK** [comment]
I have pushed a further commit to show my proposed change. Once there is agreement I will squash them to a single commit again.

**Comment by foosel** [comment]
Turn `Recv:\s*` back into `Recv: ` on both wait and processing filter and we have a deal. As I said, the whitespace there is under the control of OctoPrint, it will always be one space, and leading whitespace on the received line itself is not protocol conform and thus if it DOES happen (and consequently breaks communication in general) it should not be covered up by filters.

**Comment by foosel** [comment]
Perfect, thank you! :)

**Pull request merged**
