### PR TITLE
Fix firmware info splitting

### PR DESCRIPTION
**Pull request by cp2004**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke *err*
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
This PR adjusts the regex used to split the comm layer's firmware info parsing

#### How was it tested? How can it be tested by the reviewer?
Not yet, that's why this is a draft 🙂 The current unit tests fail because they test keys with numbers in.  The regex may need to be adjusted further, for now this is draft. Tests are currently failing

#### Any background context you want to provide?
https://github.com/cp2004/OctoPrint-EEPROM-Marlin/issues/21
https://github.com/cp2004/OctoPrint-EEPROM-Marlin/issues/16#issuecomment-744716312
https://discord.com/channels/704958479194128507/705047010641838211/788136463732047932

#### What are the relevant tickets if any?
See above

#### Further notes

~~This PR is currently draft while I have a think (or anyone else, open to suggestions!) of a better way to work with the numbers.~~ Just here as a placeholder since I told people reporting the issue it will be fixed in OctoPrint 1.6.0 😬

### CODE REVIEW

**Comment by foosel** [comment]
I see this is still in draft/wip... are you still looking into this?

**Comment by cp2004** [comment]
Every now and then, I think about it again... I have tried several ways to not break keys with numbers in but at the same time do what the above code needs to do... Still haven't come up with anything concrete, beyond what was suggested in discord. If you've got an idea, by all means go for it since my regexp knowledge is still not all that great.

**Comment by cp2004** [comment]
I think the only way I can figure out to do this would be something like this:
* The key **must** have a letter in it
* The key **can** have a number in it, but this is not required.

In the protocol of things here, would you find a key that was just numbers?

**Comment by foosel** [comment]
I think we should be able to do something like

  * the key MUST only contain uppercase letters, underscore and numbers
  * the key MUST start with an uppercase letter

There's no spec anywhere as far as I know (surprise, surprise), but from what I've seen in the past we should be fine with that definition. So I think a regex along the lines of `\s*([A-Z][A-Z0-9_]*):\s*` should get us what we want.

If that however doesn't work out, we won't get around using a tokenizer instead of a regex.

**Comment by foosel** [comment]
Pushed such a change... @cp2004 can you give it a look?

**Comment by cp2004** [comment]
Well, the tests passed, so it's better than my attempt... Might make sense to add one that tests the case this PR will fix, to correctly identify the name from a response with the time in it. I can do that, then will mark this ready to review/merge.

**Comment by foosel** [comment]
I think we should probably also add a test case for something like `1KEY` or `_KEY` getting ignored.

**Comment by cp2004** [comment]
Something like this:
```
KEY1:VALUE1 _KEY2:INVALID 123:INVALID
```
is parsed to
```python
{'KEY1': 'VALUE1 _', 'KEY2': 'INVALID 123:INVALID'}
```

Is that intended? I can't tell

**Comment by cp2004** [comment]
Tests that work are pushed, ready for merge 😄

**Comment by cp2004** [comment]
What's the point in having pre-commit file watcher if it is disabled... *sighs* it's installing.

**Comment by foosel** [comment]
That reminds me, on the weekend at PyCascades I learned about pre-commit.ci, I need to take a look at that.



> Is that intended? I can't tell

Hm... nope, it should be 

```
{"KEY1": "VALUE1 _KEY2:INVALID 123:INVALID"}
```

So that still needs some fine tuning. Hmmmm... Right now it doesn't require whitespace before the key's start. I think it should however, either that or string start. So replacing the `\s*` at the start with `(^|\s+)` should do it, but then the capture group index needs adjustment.

**Comment by foosel** [comment]
I think now we got it.

**Pull request merged**
