### PR TITLE
LOW: Documentation, use "admins" instead of ADMIN_GROUP

### PR DESCRIPTION
**Pull request by OllisGit**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
Patch of documentation
```ADMIN_GROUP``` is not available without an import in that example. So, using ```"admin"``` like it is mentioned in the above description...or add an import like
```
from octoprint.access import ADMIN_GROUP
```

#### How was it tested? How can it be tested by the reviewer?
-

#### Any background context you want to provide?
-

#### What are the relevant tickets if any?
-

#### Screenshots (if appropriate)
image

#### Further notes
-

### CODE REVIEW

**Review by foosel — CHANGES_REQUESTED** [review]
Totally agree with this needing a small fix, however it should import `ADMIN_GROUP` instead of using a magic value. Constants provided by the core are always better to avoid sudden code breakage in the future.

Also, since this is a doc change only, it's totally fine to file it against `master` so it'll be live ASAP :)

**Comment by foosel** [comment]
@OllisGit are you looking into this?

**Comment by foosel** [comment]
Or just cherry pick your changes on master and force-push to this one, then change its target

**Comment by OllisGit** [comment]
upps.. I messed up the merge request. I will create a new one!

**Pull request closed without merging**
