### PR TITLE
Enable Deflate for web socket connections

### PR DESCRIPTION
**Pull request by crysxd**
#### What does this PR do and why is it necessary?
This PR drastically reduces the bandwidth used by the web socket by enabling the `permessage-deflate` extension of the websocket protocol. This is supported by Tornado 4.5 and up.

#### How was it tested? How can it be tested by the reviewer?

I created a small benchmark by starting OctoPrint with and without compression, starting OctoApp and counting the bytes received by the web socket within 60s. With the changes, OctoPrint mirrors back the `Sec-WebSocket-Extensions: permessage-deflate` header (see screenshot).

No compression as currently in OctoPrint: 114 / 131 / 138 kb
Minimal compression as in PR: 8 / 8 / 8 kb

The increase in the data volume over time is due to the growing history message (I assume) but is negligible in the compressed tests.

Changes are also tested with Safari and Chrome, both actually already included the `Sec-WebSocket-Extensions: permessage-deflate` header to request compression

I tested the compression on a OctoPi running on a Raspberry Pi 3B (non +) and with 10 open tabs and the Resource Monitor plugin that sends a lot of data via the web socket, the CPU usage of OctoPrint was unchanged in the 18-20% range (0-400) compared to the same OctoPrint version without the compression. 

Tested on platforms:

- [x] macOS
- [x] OctoPi
- [x] Windows

#### Any background context you want to provide?

Reducing the bandwidth is essential for mobile applications and also some tunnels limit the bandwidth (e.g. TSD with 50MB/month)

#### What are the relevant tickets if any?

/

#### Screenshots (if appropriate)

Screenshot 2021-11-25 at 17 06 21

### CODE REVIEW

**Comment by crysxd** [comment]
I'm giving up on testing on Windows....spent now 3h trying to install OctoPrint on my Windows machine :D Something is wrong with the Visual C++ stuff, but not sure what :(

**Comment by cp2004** [comment]
The headers do come through, it works fine 🙂

**Comment by crysxd** [comment]
Great! Thanks for your help! 🥳

**Comment by foosel** [comment]
Yep, all good! 👍

**Pull request merged**
