### PR TITLE
✏️ Fix several typos

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -S *.po`

### CODE REVIEW

**Comment by luzpaz** [comment]
Updated description by editing the 1st post of the thread

**Review by cp2004 — CHANGES_REQUESTED** [review]
Codespell is now setup in pre-commit to run against the repository. If the configuration can be improved, please update the configuration to contribute to the future of the project. 

I am not a fan of getting multiple PRs all 'fixing typos', yes I can see that the typos are there but it would be better to leave it to the automated tools instead of spending our time reviewing these PRs.

**Comment by luzpaz** [comment]
Makes sense. Just note that the typos mentioned may not be found just yet since codespell hasn't had an update in a while. That means the dictionaries it uses aren't up to date.  Hopefully that changes. Feel free to do as you will, of course. Please advise

**Comment by foosel** [comment]
I agree with @cp2004 here, this should be detected automatically, and if it isn't yet being detected automatically the tooling needs to be improved to detect it automatically (e.g. through a PR!). We've recently been swamped with typo fix PRs and as piecemeal as they are filed they frankly add more overhead than value given our limited review resources.

**Comment by luzpaz** [comment]
fair enough

**Pull request closed without merging**
