### PR TITLE
Terminal Filters - Updated temperature regex

### PR DESCRIPTION
**Pull request by thinkyhead**
* [x] Your changes are not possible to do through a plugin and relevant to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have made sure your changes don't interfere with current development by talking it through with the maintainers, e.g. through a Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely new feature, or maintenance if it's a bug fix or improvement of existing functionality for the current stable version (no PRs against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository (no PRs from your version of master, maintenance or devel please), e.g., dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files, no dead code, ideally only one commit - rebase and squash your PR if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the .less source files, not the .css files (those are generated with lessc)
  * [x] You have tested your changes (please state how!) - ideally you have added unit tests
  * [x] You have run the existing unit tests against your changes and nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

This PR updates the default Terminal Filters regular expression for Temperature messages for Marlin 2.0.8 additions.

- Recognize the temperatures of **C**hamber, **P**robe, **R**edundant, and **L**aser cooler.
- Recognize temperature messages with negative temperatures (for a disconnected thermistor).

#### How was it tested? How can it be tested by the reviewer?

Tested and refined the filter in-place by modifying it on the running instance of OctoPrint.

#### Any background context you want to provide?

Marlin has lately added support for more heaters (and a cooler) so the letters 'C', 'P', and 'L' are now possible in temperature messages. The 'R' heater has been in Marlin since version 1.x.

#### What are the relevant tickets if any?

n/a

#### Screenshots (if appropriate)

n/a

#### Further notes

Have a nice day!

### CODE REVIEW

**Comment by cp2004** [comment]
This can target the maintenance branch, devel is probably not going to be released any time soon & it makes sense to get this out sooner rather than later.

**Comment by foosel** [comment]
This PR now does more than its advertising. Usually I'd say, let's split this up, but the changes are mostly doc changes, so I'll give this a pass and rather just leave myself a comment here for changelog compilation time:

  * Temperature regex now also recognizes `C`, `P`, `R` and `L` values as supported by Marlin, as well as negative values.
  * docs: `pip install` command should use quoted source for maximum compatibility with people's dev environments.

**Comment by thinkyhead** [comment]
Thanks for the pass. I was all ready to put that into a separate PR but you saved us both the extra work!

I was confused why the "E2E" test failed. How can I avoid that in the future?

**Comment by cp2004** [comment]
https://github.com/OctoPrint/OctoPrint/commit/46a6c58d4963470857df9cad02ec97d3055f2fe4 fixed the files API, it was broken on Friday, fixed today. Shouldn't fail again on future PRs.

**Comment by thinkyhead** [comment]
Ah, thanks! I noticed that OK messages and Temperature messages are both filtered together. It might be of value to split those up into two filters. Especially since the "Advanced OK" message is now interesting on its own. I'll see about making a new PR for that concept soon.

**Comment by foosel** [comment]
> Side note: I noticed that OK messages and Temperature messages are both filtered together.

Not intentionally, rather a side effect of the temperature responses often being joined with an `ok` (at least on Marlin, it's a separate line on RepetierFirmware).

**Pull request merged**
