### PR TITLE
Capture testballoon output from pip output instead of tmp file

### PR DESCRIPTION
**Pull request by MichaIng**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?
`setup.py` STDOUT and STDERR are printed via `pip` STDOUT until v19 and STDERR from v20 on, which can hence be parsed by the originating script directly. This allows to avoid the fragile need for a temporary file that needs to be R/W-opened by two different processes.

#### How was it tested? How can it be tested by the reviewer?
To test, OctoPrint simply needs to be started the regular war, until `octoprint.util.pip - INFO - pip installs to ...` is printed the first time.

#### Any background context you want to provide?
Usually transferring the setup info via temporary file works fine, but the fact that OctoPrint and the pip command it calls are two different processes, possibly executed by two users (e.g. invoking pip via sudo to allow global system OctoPrint instance but unprivileged OctoPrint service user) or different environment (private /tmp mount), it is a bid fragile. I personally ran into the issue that with Debian Bullseye `sysctl fs.protected_regular=2` is the default, which does not permit any user to "O_CREAT"-write to a file inside a world-writable + sticky-bit directory that is not owned by itself. In case of "octoprint" user calling custom pip command, a script which invokes pip via sudo, permitted through strict sudoers permissions, this leads to a failure: "octoprint" pip.py pre-creates the temporary file in /tmp, which by default is 1777 (world-writable + sticky bit), and even root is not able to write it via testballoon setup.py, since the method obviously implies O_CREAT, i.e. would create the file if it did not exist yet. Jep the restriction even applies to root.

I did as well search and tested a while to get the required information directly from `pip`.  `pip debug` prints a line
```
pip._vendor.certifi.where(): /usr/local/lib/python3.7/dist-packages/pip/_vendor/certifi/cacert.pem
```
which can be used to derive the install directory, but it would require quite some guessing to derive whether it's a venv/virtualenv or not 🤔.
__________
Tested with pip versions:
- [x] 20
- [x] 19
- [x] 18
- [x] 10
- [x] 9
- [x] 8

I cannot test a lower pip version (7) as it is not compatible with other Python libraries it seems:
```
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip import main
  File "/usr/local/lib/python3.7/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/lib/python3.7/dist-packages/pip/utils/__init__.py", line 23, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1712, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

But if I understand the code comments right, with pip below v8 STDOUT is preserved anyway?

### CODE REVIEW

**Comment by cp2004** [comment]
Hey @MichaIng thank you for the contribution! 

Wanted to let you know that this will be looked at, however Christmas break is coming up (and has already started for Gina) so while this will be reviewed, it will likely not be for a while. Noticed some of your linked issues so just wanted to make that clear in case you were planning anything dependent on this contribution.

**Comment by MichaIng** [comment]
Many thanks for the info. I rethought my plans and will go with a `--user` level install, which moreless equals a venv in the case where the users only purpose and use it to run OctoPrint. The construction to allow it managing a global Python setup via sudo is fragile for other reasons and always bears the risk of dependency collisions with other Python programs.

However, the PR still makes sense as it increases robustness of the testballoon install test.

**Comment by foosel** [comment]
So this is weird. I distinctly remember cursing like a sailor the day pip 8 got released and I noticed these issues. I think I even had to push a hotfix release due to `pip install` no longer providing output from `setup.py` on either stdout or stderr. Yet here we are, and suddenly it does, with the exact versions that back then didn't do a thing, regardless of what flags I threw at them.

And that worries me, because that means it might have been an effect caused not only by the pip version in question, but potentially also other parts in the python environment, like maybe `setuptools` or similar. I am worried that basically reverting to the old approach of just parsing stdout/stderr will cause issue with some installations out there. Which means I'll need to dig a bit deeper in what is actually going on in older pip versions when `install` is invoked in order to figure out what might have gone on in the past that is no longer an issue now. 

So... this might take a while.

**Comment by foosel** [comment]
Ok, that actually led faster to a result than I anticipated. The problem is/was that pip versions newer than 8 only provide the output generated by setup.py if it fails. So the old version that actually installed a package and then removed it didn't trigger it. The newer version that auto fails would have worked since 2016 even without the whole messy temp file shenanigans but for some reason I never even tested that. 

I'm very grateful for your PR triggering that realization, because this whole tempfile thing has always made me cringe whenever I had to look at it 😅

**Review by foosel — APPROVED** [review]

**Comment by MichaIng** [comment]
Great, many thanks for merging.

Yes while testing and playing a bit around with different things I realised that pip completely drops any output of the script (STDOUT+STDERR), as long as it does not error out. And when added STDERR only parsing with pip 20 and testing on older versions, suddenly the failure output was done on STDOUT, so both need to be parsed to assure backwards-compatibility. These changes in pip behaviour leave behind some worry that things could change again, but I couldn't find a way to reliably derive install target information without actually attempting an install either. At least that part is slightly more robust now 🙂.

**Comment by foosel** [comment]
> These changes in pip behaviour leave behind some worry that things could change again

The whole pip utilization in OctoPrint has so many wrappers and checks because stuff used to break all the time. Thankfully things appear to be a bit more stable these days (and I hope I didn't just jinx it 😅)

**Pull request merged**
