### PR TITLE
Small CSS typo fix

### LINKED ISSUE #3808: Wrong css name on footer
Just a small issue - the name for the footer link is footer_link in the css:
https://github.com/OctoPrint/OctoPrint/blob/3ab84ed7e4c3aaaf71fe0f184b465f25d689f929/src/octoprint/static/less/octoprint.less#L987
And its footer_link**s** in the html:
https://github.com/OctoPrint/OctoPrint/blob/3ab84ed7e4c3aaaf71fe0f184b465f25d689f929/src/octoprint/templates/footer.jinja2#L6

### PR DESCRIPTION
**Pull request by surdu**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [-] You have added yourself to the AUTHORS.md file :) (not yet, not for this 😄  )

Fixed small typo in a LESS file.

#### What are the relevant tickets if any?

Closes #3808

### CODE REVIEW

**Comment by surdu** [comment]
I'm confused about the CSS file. I've committed the CSS that I compiled using:

```
lessc -x less/octoprint.less css/octoprint.css
```

I shouldn't have ?

**Comment by cp2004** [comment]
That's fine, since it would be rebuilt by *someone*. As long as the less is modified, we don't want people changing the CSS and then it being overwritten as soon as the file watcher (at least that's how I have it setup) gets to it.

**Comment by surdu** [comment]
@cp2004 Awesome! Thanks! 

But are there any more Octoprint "by the book" ways of obtaining the CSS other than compiling them by hand? I've found something about [setting `stylesheet: less` in `config.yaml`](https://docs.octoprint.org/en/master/plugins/gettingstarted.html#style-matters-injecting-custom-css-into-the-page), but that didn't seem to work.

**Comment by cp2004** [comment]
I setup a file watcher in PyCharm Pro, that runs whenever the file is changed. I know Sass allows you to run a command that watches the file, not sure about less. 

Haven't tried setting stylesheet to less, but that should work and then you just compile before you commit.

**Comment by foosel** [comment]
Well spotted! Thank you!

**Comment by surdu** [comment]
Not my merit, but thank you 😬

**Pull request merged**
