### PR TITLE
remove Transfer-Encoding header so input is interpreted correctly by …

### PR DESCRIPTION
**Pull request by msrasheed**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?
It removes the Transfer-Encoding header when it is set to chunked so Flask handles it properly.

#### How was it tested? How can it be tested by the reviewer?
In the linked ticket, have provided some sample code that tests the behavior. 

#### What are the relevant tickets if any?
#4688

### CODE REVIEW

**Comment by msrasheed** [comment]
I'm sorry, I don't see where that checkmark in the docs ithat allows maintainers to modify a PR.

**Comment by cp2004** [comment]
Are there any potential downsides to doing this? Is it a Flask bug that it can't handle the `Transfer-Encoding` header? Perhaps it is something specific to OctoPrint's combination of Tornado/Flask.

**Comment by msrasheed** [comment]
Apparently, it is a whole thing about WSGI (and therefore werkzeug, which Flask is built on) not supporting the `Transfer-Encoding` header [among other things](https://www.b-list.org/weblog/2009/aug/10/wsgi/). 

Someone actually opened an [issue on werkzeug](https://github.com/pallets/werkzeug/issues/2346) to address this exact issue and the responses seem to be basically that it's not an issue, you're just not sending the correct headers. So werkzeug is not going to fix it, it is something the "WSGI server" has to do.

As it stands now, OctoPrint's tornado Wsgi container request handler handles chunked requests fine and assembles the body and sets the `Content-Length` header. The `Transfer-Encoding` header needs to be removed though to prevent werkzeug from returning an empty body as described in the [first comment of the issue](https://github.com/pallets/werkzeug/issues/2346#issue-1159442964).

**Comment by cp2004** [comment]
Good news. It looks OK to me, but Gina is now on her Christmas break, so this PR will be fully reviewed/merged in the new year. Thanks for your patience 🙂

**Comment by foosel** [comment]
Great catch, thank you!

**Pull request merged**
