### PR TITLE
Update black to 22.3.0

### PR DESCRIPTION
**Pull request by frenck**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

Keeping up!

#### How was it tested? How can it be tested by the reviewer?

By running `pre-commit run --all-files`

#### Any background context you want to provide?

Nope, not really.

#### What are the relevant tickets if any?

```py
result = any([False])
```

#### Screenshots (if appropriate)

No, but I do have a nice cat for you

### CODE REVIEW

**Comment by frenck** [comment]
Hmm not sure why e2e tests are broken and/or how that is related to this PR even, is the main branch in a broken state?

**Comment by cp2004** [comment]
E2E tests do seem to be a little flaky....

It definitely isn't related to this PR, I just re-ran them and it went through fine - they seem to work most of the time but every now and then give up.

**Comment by foosel** [comment]
Yeah, ever since an update of cypress they've gotten real flaky, but not enough to be able to debug. And I've actually been looking at Playwright and have been eyeing a switch to that more and more favorably due to this. 

Anyone know if it's possible to have a failing automation step only get marked as a warning instead of a failure?

**Comment by frenck** [comment]
> Anyone know if it's possible to have a failing automation step only get marked as a warning instead of a failure?

Set `continue-on-error` on the specific step, it will fail, but pass.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

**Pull request merged**
