### PR TITLE
Update docker release workflow

### PR DESCRIPTION
**Pull request by LongLiveCHIEF**
* [ ] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch if it's a completely 
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs 
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR 
    if necessary!
  * [ ] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

This PR makes some updates to the workflows that trigger events in the octoprint/octoprint-docker repo.
more info coming as I move this from draft to finished

#### How was it tested? How can it be tested by the reviewer?

- created a `workflow_dispatch` workflow on the octoprint-docker repo to test how the dispatch is received
- created a dispatcher workflow in a simple [test-repo-dispatcher](https://github.com/HackerHappyHour/test-repo-dispatcher/blob/master/.github/workflows/dispatches.yml) repository, to ensure the `github.event.release.tag_name` is the correct way to send the desired payload downstream.  I tested reception of this during the development of the tagging-strategy action, and evidence of test for this dispatch payload can be viewed by inspecting the logs for the [`4.0.0` test release action in test-repo-dispatcher](https://github.com/HackerHappyHour/test-repo-dispatcher/actions/runs/201713856), and the associated log runs at https://github.com/HackerHappyHour/tagging-strategy/actions/runs/201745061

#### Any background context you want to provide?

This PR is part of the [Stable Automated Docker Releases](https://github.com/OctoPrint/octoprint-docker/projects) project, and is related to [trigger build and tag on OctoPrint/OctoPrint master/release](https://github.com/OctoPrint/octoprint-docker/issues/50) (there will also be a companion PR in the octoprint-docker repo required to fully close the issue)

#### Further notes

Each commit will have specific details about specific changes

### CODE REVIEW

**Comment by foosel** [comment]
Ignore the bot, as we are talking GitHub workflows here `master` is fine.

**Comment by LongLiveCHIEF** [comment]
going to close this and open a new PR against maintenance branch. Rebase is conflicting with files I never touched.

**Comment by LongLiveCHIEF** [comment]
re-opening because `maintenance` doesn't have the files i need to work on, and because i would have to resolve conflicts with files unrelated to my commit.

If those conflicts clear up, then I'll re-direct the PR at that time. Until then, this is the only way I can proceed with development of the requirement.

**Comment by foosel** [comment]
I'm not entirely sure why you reduced the payload to get only the event. That way you won't be able to figure out the version that triggered things directly from the dispatch event, nor the commit sha. Only the event name, which is already implicit by attaching the action only to release events anyhow. 

You've marked this as WIP, is there still something to do or can I merge this after all?

**Comment by LongLiveCHIEF** [comment]
No, not ready to merge yet. As you say, I may need to change the payload back.

I'm still working on the tagging strategy action on the other side that will produce all the right tags from a single release.

I typically do all my work on stuff like this on the weekends (exactly the opposite of you, but for exactly the same reason lol).

If you want we can close it and I will submit instead when it's ready to go.

**Comment by LongLiveCHIEF** [comment]
No, not ready to merge yet. As you say, I may need to change the payload back.

I'm still working on the tagging strategy action on the other side that will produce all the right tags from a single release.

I typically do all my work on stuff like this on the weekends (exactly the opposite of you, but for exactly the same reason lol).

If you want we can close it and I will submit instead when it's ready to go.

**Comment by foosel** [comment]
Ah, then we'll just leave it at WIP. I just wasn't sure if that was its state due to the whole conflict situation, or due to it actually not yet being ready.

**Comment by LongLiveCHIEF** [comment]
cool.  I had made the change you referred to because the docs seemed to indicate that the ref and sha would be in the event payload itself, and so I wanted to test that and see for myself (not because I didn't trust you :wink:)

Every example I've seen added the ref and sha the same way you have it, so I was just experimenting to see if that was a "follow the leader" phenomenon, left over from a time when the payloads were different, or if it was actually needed.

Github actions really needs a testing kit so you don't have to trigger false events on your repo's to test your workflows. :-(

**Comment by LongLiveCHIEF** [comment]
This is ready to be merged.

**Pull request closed without merging**
