### PR TITLE
🚀 Modernize the code to Python 3.6+

### PR DESCRIPTION
**Pull request by eumiro**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What does this PR do and why is it necessary?

Modernizes the code to Python 3.6 and newer in several independent commits.

#### How was it tested? How can it be tested by the reviewer?

Existing unit tests.

#### Any background context you want to provide?

Inspired by `pyupgrade`, but used only some features.

#### What are the relevant tickets if any?

None

#### Screenshots (if appropriate)

None

#### Further notes

Did not touch the strings (`f-strings` are cool!). And how about converting directory/file manipulation code to `pathlib.Path`?

And no, still no 3d printer.

### CODE REVIEW

**Comment by foosel** [comment]
I'm happy to merge this in general, however could you exclude the files in `src/vendor`? Those are external libraries I had to bundle in order to work around the one or other crippling bug that had not been fixed upstream, and I try to keep those as close to the original as possible in order to still be able to easily see if they can be unvendored again during regular diffs.

**Review by foosel — CHANGES_REQUESTED** [review]
I'm happy to merge this in general, however could you exclude the files in `src/octoprint/vendor`? Those are external libraries I had to bundle in order to work around the one or other crippling bug that had not been fixed upstream, and I try to keep those as close to the original as possible in order to still be able to easily see if they can be unvendored again during regular diffs.

**Comment by eumiro** [comment]
This was some git juggling but finally I reverted all changes to that subdirectory.

**Review by foosel — APPROVED** [review]

**Comment by foosel** [comment]
Thank you 😊

**Pull request merged**
