### PR TITLE
Migrate from netifaces to netifaces2

### PR DESCRIPTION
**Pull request by MichaIng**
* [x] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [x] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [x] Your PR targets OctoPrint's `devel` branch if it's a completely
    new feature, or `maintenance` if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against `master` or anything else please)
  * [x] Your PR was opened from a custom branch on your repository
    (no PRs from your version of `master`, `maintenance`, or `devel`
    please), e.g. `dev/my_new_feature` or `fix/my_bugfix`
  * [x] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [x] Your changes follow the existing coding style
  * [x] If your changes include style sheets: You have modified the
    `.less` source files, not the `.css` files (those are generated
    with `lessc`)
  * [x] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [x] You have run the existing unit tests against your changes and
    nothing broke
  * [x] You have added yourself to the `AUTHORS.md` file :)

#### What does this PR do and why is it necessary?

The original project has been abandoned two years ago: https://pypi.org/project/netifaces/

The new project claims to be nearly fully API-compatible: https://pypi.org/project/netifaces2/

Note the differences regarding `gateways` function and `AF_` constants.

The OctoPrint code however does not seem to use any of those, I tested the web interface without facing issues or errors, so given the CI/CD is passed, it should be fine.

#### How was it tested? How can it be tested by the reviewer?

Checked OctoPrint code for use of `netifaces.gateways()` and `netifaces.AF_LINK`, which is both not the case. Looped through all parts of the web interface and checked OctoPrint logs for any errors.

### CODE REVIEW

**Comment by MichaIng** [comment]
Since the E2E tests fail on all open PRs, I guess it is unrelated.

**Comment by foosel** [comment]
> Since the E2E tests fail on all open PRs, I guess it is unrelated.

Those failed for the same reason that 1.8.7 had to be pushed - a breaking change in a second level third party dependency.

So yes, something you can ignore on your end. I'd like you however to please file this change against `maintenance` instead of `devel` - it's not a breaking new feature, as far as I understand it's a drop-in replacement for an abandoned library and as thus classifies as "improvement".

It won't make it into 1.9.0 however, that's already been frozen and in fact I'm just now sitting on the final release announcement for the first RC after spending the past days compiling the changelog, fixing last minute issues and so on (hence also the delay in getting back to you here)

**Review by foosel — CHANGES_REQUESTED** [review]
Please file against `maintenance` as mentioned.

**Review by foosel — APPROVED** [review]

**Comment by foosel** [comment]
Thank you!

**Comment by MichaIng** [comment]
Thanks for merging!

Btw, I recognised that dependabot isn't able to detect dependencies in `setup.py` the way they are defined via two additional levels of variables. I guess you are aware of this, otherwise I'm suggestion to refactor it to benefit from dependabot. I can open a PR about that, if you want 🙂.

**Comment by foosel** [comment]
I'm aware of that, however have not yet have found the time to look at it again. The last time I looked at it, `setup.py` still needed to be very dynamic due to the `pip` versions out there on OctoPi not yet supporting testing of py versions etc, and I couldn't find a way to make things work with dependabot back then. And since then I haven't had a chance to look again. If you want to look into this (and in a way it keeps things maintainable), that would be awesome!

**Pull request merged**
