### PR TITLE
A small css bug that causes a lot of havoc in the styles when trying …

### PR DESCRIPTION
**Pull request by LazeMSS**
Just a small fix to change the drop down menus in the accordion menus being style like the headers icon.

### CODE REVIEW

**Comment by foosel** [comment]
Can you take a look at the failing check?

**Comment by cp2004** [comment]
`pre-commit run --hook-stage manual --all-files`, or just make the change suggested by prettier.

**Comment by LazeMSS** [comment]
@cp2004  is it me or ?

**Comment by foosel** [comment]
You had a failing check: https://github.com/OctoPrint/OctoPrint/pull/4014/checks?check_run_id=1866705884 All checks should be green for this to be merged to keep the code consistent. That's what we were both referring to. I quickly fixed it myself just now, but in the future please also run `pre-commit` (refer to item 9 [here](https://github.com/OctoPrint/OctoPrint/blob/master/CONTRIBUTING.md#pull-requests)) on your end and take note of the checks run against your PRs ;)

**Review by foosel — APPROVED** [review]

**Pull request merged**
