### PR TITLE
Request wakelock when viewing webcam

### LINKED ISSUE #4564: [Request] WakeLock when viewing webcam
### Is your feature request related to a problem? Please describe.

When monitoring prints from my phone via a browser, the phone screen goes to sleep after the standard amount of time, instead of staying awake to do the playing video.

### Describe the solution you'd like

I would like the client code to use the [WakeLock web API](https://developer.mozilla.org/en-US/docs/Web/API/WakeLock) to signal to the device that it should stay awake. I imagine this could be added in this function:
https://github.com/OctoPrint/OctoPrint/blob/2e1ec42c5b7602be7bb57b1792598a851441c156/src/octoprint/static/js/app/viewmodels/control.js#L558

I am more than happy to implement this myself and submit a PR. The reason I'm creating an issue first is to determine if this is indeed the best place to add this or if this is even a feature that would be considered were I to create such a PR.

### Describe alternatives you've considered

_No response_

### Additional context

I use the [TouchUI plugin](https://github.com/BillyBlaze/OctoPrint-TouchUI). It's possible this would be better suited to that plugin.

### PR DESCRIPTION
**Pull request by szh**
* [ ] Your changes are not possible to do through a plugin and relevant
    to a large audience (ideally all users of OctoPrint)
  * [ ] If your changes are large or otherwise disruptive: You have
    made sure your changes don't interfere with current development by
    talking it through with the maintainers, e.g. through a
    Brainstorming ticket
  * [ ] Your PR targets OctoPrint's devel branch if it's a completely
    new feature, or maintenance if it's a bug fix or improvement of
    existing functionality for the current stable version (no PRs
    against master or anything else please)
  * [ ] Your PR was opened from a custom branch on your repository
    (no PRs from your version of master, maintenance or devel please),
    e.g. dev/my_new_feature or fix/my_bugfix
  * [ ] Your PR only contains relevant changes: no unrelated files,
    no dead code, ideally only one commit - rebase and squash your PR
    if necessary!
  * [ ] Your changes follow the existing coding style
  * [ ] If your changes include style sheets: You have modified the
    .less source files, not the .css files (those are generated with
    lessc)
  * [ ] You have tested your changes (please state how!) - ideally you
    have added unit tests
  * [ ] You have run the existing unit tests against your changes and
    nothing broke
  * [ ] You have added yourself to the AUTHORS.md file :)

#### What are the relevant tickets if any?

Resolves #4564

### CODE REVIEW

**Comment by cp2004** [comment]
I think it would be good if this could be a configurable option, not always applied.

**Comment by foosel** [comment]
If only turned on in case of an enabled config option (which by default may be enabled) I'm open to this being merged. The https-only thing limits this somewhat severely (most people won't know how to set up a secure context or that they already have a self-signed one available on OctoPi), but having it available by default to those that do is a good idea as long as it can be switched off.

**Comment by cp2004** [comment]
@szh, do you know if you will you be working on this?

**Comment by szh** [comment]
> @szh, do you know if you will you be working on this?

I haven't had a chance to make this into a config option. If you want to do that part I can pull it into my PR.

**Pull request closed without merging**
